apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-d4zd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iysl-tenant/rhtap-demo-app/hacbs-test-project-d4zd@sha256:950b33af0782f0cd4b5191a2d198b0411d7075e38c183167289cd673aa150a95
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
