apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-d4zd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iysl-tenant/rhtap-demo-app/hacbs-test-project-d4zd@sha256:59172ac44e264c65cad0cfb476cdf8e6ce582c41791392c51b2412afb8ff5fa5
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
