apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-d4zd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-d4zd
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-d4zd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-d4zd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-d4zd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iysl-tenant/rhtap-demo-app/hacbs-test-project-d4zd@sha256:950b33af0782f0cd4b5191a2d198b0411d7075e38c183167289cd673aa150a95
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
